edition = "2024"
max_width = 80
newline_style = "Unix"
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
imports_layout = "Vertical"
use_field_init_shorthand = true
force_multiline_blocks = true
match_block_trailing_comma = true
enum_discrim_align_threshold = 60
struct_field_align_threshold = 60
inline_attribute_width = 60
wrap_comments = true
normalize_comments = true
format_code_in_doc_comments = true
doc_comment_code_block_width = 80
normalize_doc_attributes = true
format_strings = true
